### ISSUE TITLE
Create Frontend

### ISSUE THREAD

**Issue by AdityaPunetha** [upes-open/OSC-Medical-Analysis-Application-Using-ML#1]
A basic react website has already been initialized in the backend folder. Construct a form like interface where one can upload an image. After uploading an image the user would press the submit button and the image would be sent to a backend api for inference.  In case the backend is not prepared at the time of creating the frontend, use a place holder api. After a successful inference, show the user the result. Is case of an error, show a popup with the error code received.

**Comment by iamrehmankhan** [comment]
Kindly assign this issue to me.

**Comment by siddhantsingh9811** [comment]
> Kindly assign this issue to me.

Try to use React for the frontend if possible

**Comment by siddhantsingh9811** [comment]
HI @AdityaPunetha can i start working on this issue as there hasn't been any updates to it in about 10 days?
