### ISSUE TITLE
Integrate Model and API

### ISSUE THREAD

**Issue by AdityaPunetha** [upes-open/OSC-Medical-Analysis-Application-Using-ML#5]
After both the model( #4 ) and the api( #3 ) has been constructed, create appropriate functions within app.py that perform inference on the images using the saved model.

**Comment by siddhantsingh9811** [comment]
This issue was also resolved in this pull request
https://github.com/upes-open/OSC-Medical-Analysis-Application-Using-ML/pull/9
kindly close it
